[project]
  name            = "imap-report-collector"
  version         = "3.0.3"
  requires-python = ">=3.14"
  dependencies    = [
    "aeth-ext[sftp, async]>=8.0.6",
    "aiologic>=0.16.0",
    "heartrate>=0.2.2",
    "imap-tools>=1.11.1",
    "pydantic-settings>=2.14.1",
    "rich>=15.0.0",
    "tzdata>=2026.1",
  ]

  [project.scripts]
    run-app-imap-report-collector = "imap_report_collector.__main__:run_app"

[dependency-groups]
  dev = [
    "aeth-devkit>=7.0.2",
    "poethepoet>=0.46.0",
    "pyright>=1.1.411",
  ]

[build-system]
  requires      = ["uv_build>=0.11.2,<0.12.0"]
  build-backend = "uv_build"

[tool.coverage.run]
  data_file   = ".cache/.coverage"
  source_pkgs = [
    "scheduled_invoice_processor",
    "imap_report_collector"
  ]                                                                       # setup-project added: "imap_report_collector"

[tool.coverage.report]
  show_missing = true

[tool.coverage.html]
  directory = ".cache/htmlcov"

[tool.coverage.xml]
  output = ".cache/coverage.xml"

[tool.coverage.lcov]
  output = ".cache/coverage.lcov"

[tool.docker]
  # Paths relative to /app that the entrypoint will chown to nonroot:nonroot.
  # Typically these are directories that will be bind-mounted as Docker volumes.
  chown_paths = [
    "persisted_data",
  ]
  mkdirs      = [""]

[tool.poe]
  include_script = [
    { script = "aeth_devkit:tasks", executor = { type = "uv", frozen = true } }
  ]

[tool.pyright]
  typeCheckingMode = "standard"

  verboseOutput          = true
  useLibraryCodeForTypes = true

  enableReachabilityAnalysis  = true
  analyzeUnannotatedFunctions = true
  deprecateTypingAliases      = true

  reportPropertyTypeMismatch          = true
  reportMissingTypeStubs              = false
  reportImportCycles                  = true
  reportUntypedFunctionDecorator      = true
  reportUntypedClassDecorator         = true
  reportUntypedNamedTuple             = true
  reportPrivateUsage                  = true
  # reportConstantRedefinition          = true
  reportDeprecated                    = true
  # reportMissingSuperCall              = true
  reportUninitializedInstanceVariable = true
  reportMissingParameterType          = true
  # reportMissingTypeArgument           = true
  reportUnnecessaryIsInstance         = true
  reportUnnecessaryCast               = true
  reportUnnecessaryComparison         = true
  reportUnnecessaryContains           = true
  reportInvalidStubStatement          = true
  reportUnnecessaryTypeIgnoreComment  = true
  reportMatchNotExhaustive            = true
  reportUnreachable                   = true
  reportImplicitOverride              = true
  reportMissingTypeArgument           = false

  executionEnvironments = [{ root = "src", extraPaths = ["src"] }]

[tool.pytest.ini_options]
  addopts      = [
    "--cov",
    "--cov-report=term-missing",
    "--strict-markers",
    "--strict-config",
    "-ra"
  ]
  cache_dir    = ".cache/pytest"
  testpaths    = ["tests"]
  xfail_strict = true
  asyncio_mode = "auto"

[tool.ruff]
  cache-dir = ".cache/ruff"

  src = ["./src"]

  exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "dist",
    "node_modules",
    "venv",
  ]

  fix = true

  indent-width = 2
  line-length  = 135

  [tool.ruff.format]
    docstring-code-format = true

  [tool.ruff.lint]
    extend-select = [
      "A",
      "ANN001",
      "ASYNC",
      "B",
      "C4",
      "C90",
      "DTZ",
      "FBT003",
      "LOG",
      "N",
      "NPY",
      "PD",
      "PERF",
      "PL",
      "PYI",
      "RUF",
      "T10",
      "TC",
      "UP",
    ]
    ignore        = [
      "A004",
      "PD008",
      "PD009",
      "PLC0415",
      "PLR0913",
      "PLW0603",
      "PIE790",
    ]

    [tool.ruff.lint.isort]
      combine-as-imports = true
      known-first-party  = ["imap_report_collector"]

      [tool.ruff.lint.isort.import-heading]
        first-party      = "First party imports"
        future           = "Future imports"
        local-folder     = "Local folder imports"
        standard-library = "Standard library imports"
        third-party      = "Third party imports"

[tool.tombi]
  toml-version = "v1.1.0"

  [tool.tombi.files]
    exclude = [
      ".bzr",
      ".direnv",
      ".eggs",
      ".git",
      ".git-rewrite",
      ".hg",
      ".mypy_cache",
      ".nox",
      ".pants.d",
      ".pytype",
      ".ruff_cache",
      ".svn",
      ".tox",
      ".venv",
      "__pypackages__",
      "_build",
      "buck-out",
      "dist",
      "node_modules",
      "venv",
    ]

  [tool.tombi.format.rules]
    indent-sub-tables               = true
    indent-table-key-value-pairs    = true
    key-value-equals-sign-alignment = true
    trailing-comment-alignment      = true

[tool.uv]
  environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
  ]

  [tool.uv.sources]
    aeth-ext    = [
      { index = "SFTPyPI", marker = "sys_platform == 'linux'" },
      { path = "../aeth_ext", editable = true, marker = "sys_platform == 'win32'" },
    ]
    aeth-devkit = [
      { index = "SFTPyPI" },
      # , marker = "sys_platform == 'linux'"
      # { path = "../aeth-devkit", editable = true, marker = "sys_platform == 'win32'" },
    ]

  [[tool.uv.index]]
    name        = "SFTPyPI"
    url         = "https://pypi.sweetfiretobacco.com/jacob.ogden/internal/+simple"
    publish-url = "https://pypi.sweetfiretobacco.com/jacob.ogden/internal/"
    explicit    = true
