# ruff: noqa: ANN001
# pyright: reportMissingParameterType=false

levels = ...
lightnesses = ...
lexer = ...
formatter = ...

def highlight_python(code): ...
def highlight_python_and_ranges(code): ...
def highlight_stack_frame(frame): ...
def trace(files=..., port=..., host=..., browser=..., daemon=...): ...

open_sentinel = ...
close_sentinel = ...

def highlight_ranges(source, frames):  # -> LiteralString:
  ...
def queue_counter(queue, n):  # -> Counter[Any]:
  ...
